#!/bin/sh
# Shell script to run docuteam packer under OS X

cd "$(dirname "$0")/../docuteam packer"
../../../java/Contents/Home/bin/java -Xms512M -Xmx2048M -Xdock:icon=../Resources/DocuteamPacker.icns -Xdock:name="docuteam packer" -cp config/:./:docuteam-packer-${project.version}.jar -Dfile.encoding=utf-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager ch.docuteam.packer.gui.launcher.LauncherView &

# Optional application parameters:
# -configDir="/Users/MrX/packer-config"
# -open="/Users/MrX/SIPs/example.zip"
# -help